import { useEffect, useMemo, useState } from 'react';
import { Activity, BedDouble, Check, ChevronRight, Circle, Clock3, Hospital, Plus, RefreshCw, Search, ShieldCheck, UserPlus, Wrench, X } from 'lucide-react';
import { SectionHeading } from '../ui';
import { apiUrl } from '../api';

const statusLabels = { available: 'Available', occupied: 'Occupied', reserved: 'Reserved', cleaning: 'Under Cleaning', maintenance: 'Under Maintenance' };
const statusColors = { available: '#16a34a', occupied: '#dc2626', reserved: '#eab308', cleaning: '#2563eb', maintenance: '#111827' };
const staffHeader = (sessionToken) => ({ Authorization: `Bearer ${sessionToken}`, 'X-AAS-Staff': 'demo-hospital-staff' });

export default function BedAvailability({ sessionToken, go, staffMode = false }) {
  const [snapshot, setSnapshot] = useState(null);
  const [selectedWard, setSelectedWard] = useState(null);
  const [wardFilter, setWardFilter] = useState('All');
  const [genderFilter, setGenderFilter] = useState('All');
  const [statusFilter, setStatusFilter] = useState('All');
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [actionError, setActionError] = useState('');
  const [newWard, setNewWard] = useState({ name: '', unit: '', prefix: '' });
  const load = async () => { setLoading(true); try { const response = await fetch(apiUrl(staffMode ? '/api/staff/beds' : '/api/beds/availability'), { headers: staffMode ? staffHeader(sessionToken) : {} }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || 'Unable to load bed availability.'); setSnapshot(result.data); setSelectedWard((current) => current ? result.data.wards.find((ward) => ward.id === current.id) || current : null); setError(''); } catch (loadError) { setError(loadError.message); } finally { setLoading(false); } };
  useEffect(() => { load(); const timer = window.setInterval(load, 5000); return () => window.clearInterval(timer); }, [staffMode, sessionToken]);

  const wards = useMemo(() => (snapshot?.wards || []).filter((ward) => {
    const matchesWard = wardFilter === 'All' || ward.unit === wardFilter || ward.name === wardFilter;
    const matchesGender = genderFilter === 'All' || ward.gender === genderFilter;
    const matchesSearch = `${ward.name} ${ward.unit} ${ward.availableBedNumbers.join(' ')}`.toLowerCase().includes(query.toLowerCase());
    const matchesStatus = statusFilter === 'All' || (staffMode && ward.beds.some((bed) => bed.status === statusFilter));
    return matchesWard && matchesGender && matchesSearch && matchesStatus;
  }), [snapshot, wardFilter, genderFilter, statusFilter, query, staffMode]);

  if (loading && !snapshot) return <div className="loading"><span className="spinner" /><span>Loading bed availability…</span></div>;
  if (error && !snapshot) return <div className="error-state"><strong>Bed availability unavailable.</strong><p>{error}</p><button className="secondary-button" onClick={load}><RefreshCw size={15} /> Try again</button></div>;
  if (!snapshot) return null;
  const totals = snapshot.totals;
  return <>
    <SectionHeading eyebrow={staffMode ? 'Authorized hospital staff' : 'Hospital services'} title="Bed Availability" copy={staffMode ? 'Manage ward beds, admissions and patient transfers.' : 'See the hospital\'s latest recorded ward and bed availability.'} action={<div className="bed-heading-actions"><span className="last-updated"><Clock3 size={14} /> Last updated {timeAgo(snapshot.lastUpdated)}</span>{staffMode ? <button className="secondary-button" onClick={() => go('hospital-availability')}><Hospital size={15} /> Public view</button> : <button className="secondary-button" onClick={() => go('bed-staff')}><ShieldCheck size={15} /> Staff console</button>}<button className="icon-button" onClick={load} aria-label="Refresh bed availability" title="Refresh"><RefreshCw size={16} /></button></div>} />
    {actionError && <p className="bed-action-error" role="alert">{actionError}</p>}
    {staffMode && <div className="bed-add-ward"><strong>Add ward</strong><input placeholder="Ward name" value={newWard.name} onChange={(event) => setNewWard((current) => ({ ...current, name: event.target.value }))} /><input placeholder="Unit code" value={newWard.unit} onChange={(event) => setNewWard((current) => ({ ...current, unit: event.target.value }))} /><input placeholder="Bed prefix" value={newWard.prefix} onChange={(event) => setNewWard((current) => ({ ...current, prefix: event.target.value }))} /><button className="secondary-button small" onClick={async () => { try { const response = await fetch(apiUrl('/api/staff/wards'), { method: 'POST', headers: { ...staffHeader(sessionToken), 'Content-Type': 'application/json' }, body: JSON.stringify({ ...newWard, gender: 'Unisex' }) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || 'Unable to add ward.'); setSnapshot(result.data); setNewWard({ name: '', unit: '', prefix: '' }); setActionError(''); } catch (wardError) { setActionError(wardError.message); } }}><Plus size={14} /> Add ward</button></div>}
    <section className="bed-summary-grid">{[['Total Beds', totals.total, 'total'], ['Occupied Beds', totals.occupied, 'occupied'], ['Available Beds', totals.available, 'available'], ['Reserved Beds', totals.reserved, 'reserved'], ['Under Cleaning / Maintenance', totals.cleaning + totals.maintenance, 'maintenance']].map(([label, value, tone]) => <div className={`bed-summary-card ${tone}`} key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>
    <div className="bed-legend"><strong>Bed status</strong>{Object.entries(statusLabels).map(([status, label]) => <span key={status}><i style={{ background: statusColors[status] }} />{label}</span>)}</div>
    <div className="bed-filters"><label className="bed-search"><Search size={16} /><input placeholder="Search bed number" value={query} onChange={(event) => setQuery(event.target.value)} /></label><select value={wardFilter} onChange={(event) => setWardFilter(event.target.value)}><option>All</option>{[...new Set(snapshot.wards.map((ward) => ward.unit))].map((ward) => <option key={ward}>{ward}</option>)}</select><select value={genderFilter} onChange={(event) => setGenderFilter(event.target.value)}><option>All</option><option>Male</option><option>Female</option><option>Unisex</option></select>{staffMode && <select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="All">All statuses</option>{Object.entries(statusLabels).map(([status, label]) => <option key={status} value={status}>{label}</option>)}</select>}</div>
    <div className="bed-ward-grid">{wards.map((ward) => <WardCard key={ward.id} ward={ward} staffMode={staffMode} onClick={() => setSelectedWard(ward)} />)}</div>
    {!wards.length && <div className="empty-state"><BedDouble size={24} /><strong>No wards match these filters.</strong><p>Try another ward, gender or bed search.</p></div>}
    {selectedWard && <BedWardDetail ward={selectedWard} wards={snapshot.wards} staffMode={staffMode} sessionToken={sessionToken} onClose={() => setSelectedWard(null)} onUpdated={(next) => { setSnapshot(next); setSelectedWard(next.wards.find((ward) => ward.id === selectedWard.id)); }} onError={setActionError} />}
  </>;
}

function WardCard({ ward, staffMode, onClick }) { return <button className="bed-ward-card" onClick={onClick}><div className="bed-ward-head"><span className="bed-ward-icon"><BedDouble size={19} /></span><span className="bed-ward-open"><span>{ward.available} available</span><ChevronRight size={16} /></span></div><h2>{ward.name}</h2><p>{ward.unit}{ward.gender !== 'Unisex' ? ` · ${ward.gender}` : ''}</p><div className="bed-ward-metrics"><div><small>Total</small><strong>{ward.total}</strong></div><div><small>Occupied</small><strong>{ward.occupied}</strong></div><div className="available"><small>Available</small><strong>{ward.available}</strong></div><div><small>Reserved</small><strong>{ward.reserved}</strong></div></div><div className="bed-bar"><span style={{ width: `${ward.total ? Math.min(100, ((ward.occupied + ward.reserved) / ward.total) * 100) : 0}%` }} /></div><small className="bed-card-foot">{staffMode ? `${ward.cleaning + ward.maintenance} cleaning / maintenance` : `View available bed numbers`}</small></button>; }

function BedWardDetail({ ward, wards, staffMode, sessionToken, onClose, onUpdated, onError }) {
  const [admission, setAdmission] = useState({ patientName: '', bedId: '' });
  const [newBed, setNewBed] = useState('');
  const [saving, setSaving] = useState(false);
  const request = async (url, options = {}) => { setSaving(true); try { const response = await fetch(apiUrl(url), { ...options, headers: { ...(options.headers || {}), ...(staffMode ? staffHeader(sessionToken) : {}) } }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || 'Bed update failed.'); onUpdated(result.data); onError(''); } catch (error) { onError(error.message); } finally { setSaving(false); } };
  const assign = () => request('/api/staff/admissions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ patientName: admission.patientName, wardId: ward.id, bedId: admission.bedId }) });
  const changeStatus = (bed, status) => request(`/api/staff/beds/${bed.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status, patientName: bed.patientName }) });
  const transfer = (bed, wardId) => request(`/api/staff/beds/${bed.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ wardId, patientName: bed.patientName }) });
  const addBed = () => request('/api/staff/beds', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ wardId: ward.id, number: newBed, gender: ward.gender }) });
  const beds = ward.beds || [];
  return <div className="bed-detail-overlay" role="dialog" aria-modal="true"><section className="bed-detail-drawer"><div className="bed-detail-top"><div><p className="eyebrow">WARD DETAILS</p><h2>{ward.name} · {ward.unit}</h2><span>{ward.total} total · {ward.available} available</span></div><button className="icon-button" onClick={onClose} aria-label="Close ward details"><X size={18} /></button></div><div className="available-bed-list"><h3>Available Beds</h3>{ward.availableBedNumbers.length ? <div>{ward.availableBedNumbers.map((number) => <span key={number} className="available-bed-chip"><Check size={13} />{number}</span>)}</div> : <p>No beds are currently available.</p>}</div>{staffMode && <><div className="staff-admission-box"><div className="bed-detail-top"><h3><UserPlus size={16} /> New admission</h3><Activity size={17} /></div><div className="staff-inline-fields"><input placeholder="Patient name" value={admission.patientName} onChange={(event) => setAdmission((current) => ({ ...current, patientName: event.target.value }))} /><select value={admission.bedId} onChange={(event) => setAdmission((current) => ({ ...current, bedId: event.target.value }))}><option value="">Select available bed</option>{beds.filter((bed) => bed.status === 'available').map((bed) => <option key={bed.id} value={bed.id}>{bed.number}</option>)}</select><button className="primary-button small" disabled={saving || !admission.patientName || !admission.bedId} onClick={assign}><UserPlus size={14} /> Admit</button></div></div><div className="staff-add-bed"><input placeholder="New bed number, e.g. G-M-31" value={newBed} onChange={(event) => setNewBed(event.target.value)} /><button className="secondary-button small" disabled={saving || !newBed} onClick={addBed}><Plus size={14} /> Add bed</button></div></>}{staffMode && <div className="staff-bed-list"><h3>Manage beds</h3>{beds.map((bed) => <div className="staff-bed-row" key={bed.id}><span><strong>{bed.number}</strong><small>{bed.status === 'occupied' ? bed.patientName : statusLabels[bed.status]}</small></span><select value={bed.status} onChange={(event) => changeStatus(bed, event.target.value)}><option value="available">Available</option><option value="occupied">Occupied</option><option value="reserved">Reserved</option><option value="cleaning">Under Cleaning</option><option value="maintenance">Under Maintenance</option></select>{bed.status === 'occupied' && <select value={bed.wardId} onChange={(event) => transfer(bed, event.target.value)}><option value={bed.wardId}>Transfer ward</option>{wards.filter((destination) => destination.id !== bed.wardId && destination.available > 0).map((destination) => <option key={destination.id} value={destination.id}>{destination.unit}</option>)}</select>}</div>)}</div>}</section></div>;
}

function timeAgo(timestamp) { const seconds = Math.max(0, Math.floor((Date.now() - new Date(timestamp).getTime()) / 1000)); if (seconds < 10) return 'just now'; if (seconds < 60) return `${seconds} seconds ago`; const minutes = Math.floor(seconds / 60); return `${minutes} minute${minutes === 1 ? '' : 's'} ago`; }
