import { useEffect, useState } from 'react';
import {
  ArrowRight, Bell, Check, Edit3, FileText, HeartPulse, History, IdCard, Info, LogOut, Phone,
  Pill, Save, ShieldCheck, Stethoscope, Ticket, UserRound
} from 'lucide-react';
import { SectionHeading } from '../ui';
import { apiUrl } from '../api';
import { consentHistory, consentItems } from '../data';

// Screen 8 — Notifications (in-app; generated by prototype events).
export function Notifications({ notifications, onMarkAllRead }) {
  const unread = notifications.filter((n) => n.unread).length;
  return (
    <>
      <SectionHeading eyebrow="Stay informed" title="Notifications" copy="Helpful updates from your care journey."
        action={unread > 0 && <button className="help-link" onClick={onMarkAllRead}><Check size={15} /> Mark all read ({unread})</button>} />
      {notifications.length === 0
        ? <div className="empty-state"><Bell size={24} /><strong>No notifications yet</strong><p>Updates about tokens, medicines and follow-ups will appear here.</p></div>
        : (
          <section className="notification-list">
            {notifications.map((n) => {
              const Icon = { ticket: Ticket, pill: Pill, stethoscope: Stethoscope, idcard: IdCard }[n.icon] || Bell;
              return (
                <div className={`notification-item ${n.unread ? 'unread' : ''}`} key={n.id}>
                  <div className="notification-icon"><Icon size={19} /></div>
                  <div>
                    <span>{n.kind}</span>
                    <strong>{n.title}</strong>
                    <p>{n.body}</p>
                  </div>
                  {n.unread && <span className="unread-label">New</span>}
                </div>
              );
            })}
          </section>
        )}
      <p className="screen-note">Notifications are generated inside the prototype. No SMS is sent.</p>
    </>
  );
}

// Screen 10 — Basic consent view.
export function Consent({ consents, onToggle, go }) {
  const [showHistory, setShowHistory] = useState(false);
  return (
    <>
      <SectionHeading eyebrow="Your privacy" title="Your data & consent" copy="You decide what AAS can use. Change access any time." />
      <section className="consent-card">
        <div className="consent-header">
          <span className="consent-icon"><ShieldCheck size={22} /></span>
          <div>
            <h2>What AAS can access</h2>
            <p>Only what's needed to help you — nothing more.</p>
          </div>
        </div>
        {consentItems.map((item) => (
          <div className="consent-row" key={item.id}>
            <div className="consent-text">
              <strong>{item.label}</strong>
              <span>{item.note}</span>
            </div>
            <button
              className={`toggle ${consents[item.id] ? 'on' : ''}`}
              role="switch"
              aria-checked={consents[item.id]}
              aria-label={`${item.label} access`}
              onClick={() => onToggle(item.id)}
            >
              <i />
            </button>
            <span className={`access-badge ${consents[item.id] ? '' : 'off'}`}>
              {consents[item.id] ? <><Check size={14} /> Allowed</> : 'Blocked'}
            </span>
          </div>
        ))}
        <div className="consent-actions">
          <button className="secondary-button" onClick={() => setShowHistory(!showHistory)}><History size={16} /> View consent history</button>
          <button className="ghost-button" onClick={() => go('audit')}><Info size={15} /> See recent activity</button>
        </div>
        {showHistory && (
          <div className="consent-history">
            {consentHistory.map((entry) => (
              <div className="history-row" key={entry.when}><span className="history-dot" /><div><strong>{entry.text}</strong><time>{entry.when}</time></div></div>
            ))}
          </div>
        )}
        <p className="screen-note">Demo consent view. Legal details would sit behind an information link in the full product.</p>
      </section>
    </>
  );
}

// Screen 11 — Basic audit log (read-only).
export function Audit({ audit }) {
  return (
    <>
      <SectionHeading eyebrow="Transparency" title="Recent activity" copy="A simple read-only history of actions in your account." />
      <section className="audit-card">
        {audit.map((entry, index) => (
          <div className="audit-row" key={entry.id}>
            <time>{entry.time}</time>
            <span className="audit-dot" />
            <p>{entry.text}</p>
            {index === 0 && <span className="demo-chip">DEMO DATA</span>}
          </div>
        ))}
      </section>
      <p className="screen-note">Prototype demonstration only — not a complete audit system.</p>
    </>
  );
}

const blankProfile = {
  name: '', age: '', gender: '', height: '', bloodGroup: '', aadhaarNumber: '',
  ayushmanCardNumber: '', mobile: '', address: '', emergencyContact: ''
};

const profileForm = (data) => ({ ...blankProfile, ...data });

const isMasked = (value) => /^(?:X+-?)+\d{4}$/.test(String(value || ''));
const validPhone = (value) => /^(?:\d{10}|91\d{10})$/.test(String(value || '').replace(/\D/g, ''));

const validateProfile = (form) => {
  const errors = {};
  if (!form.name.trim()) errors.name = 'Enter the patient name.';
  if (!/^\d+$/.test(String(form.age)) || Number(form.age) < 0 || Number(form.age) > 120) errors.age = 'Enter an age between 0 and 120.';
  if (!form.gender) errors.gender = 'Select a gender.';
  if (!/^\d+$/.test(String(form.height)) || Number(form.height) < 40 || Number(form.height) > 250) errors.height = 'Enter height between 40 and 250 cm.';
  if (!form.bloodGroup) errors.bloodGroup = 'Select a blood group.';
  if (!validPhone(form.mobile)) errors.mobile = 'Enter 10 digits, with an optional +91 prefix.';
  if (!validPhone(form.emergencyContact)) errors.emergencyContact = 'Enter 10 digits, with an optional +91 prefix.';
  if (form.address.trim().length < 5) errors.address = 'Enter a complete address.';
  if (form.aadhaarNumber && !isMasked(form.aadhaarNumber) && !/^\d{12}$/.test(form.aadhaarNumber)) errors.aadhaarNumber = 'Aadhaar must be exactly 12 digits.';
  if (form.ayushmanCardNumber && !isMasked(form.ayushmanCardNumber) && !/^[A-Z0-9/-]{6,30}$/i.test(form.ayushmanCardNumber)) errors.ayushmanCardNumber = 'Use 6-30 letters, numbers, hyphens or slashes.';
  return errors;
};

// Profile — protected patient details and quick links.
export function Profile({ go, onLogout, sessionToken, onProfileSaved }) {
  const [form, setForm] = useState(blankProfile);
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState(false);
  const [saving, setSaving] = useState(false);
  const [errors, setErrors] = useState({});
  const [requestError, setRequestError] = useState('');
  const [notice, setNotice] = useState('');

  const authHeaders = { Authorization: `Bearer ${sessionToken}` };

  useEffect(() => {
    let active = true;
    fetch(apiUrl('/api/profile'), { headers: authHeaders })
      .then(async (response) => {
        const result = await response.json();
        if (!response.ok || !result.success) throw new Error(result.message || 'Unable to load profile.');
        if (active) setForm(profileForm(result.data));
      })
      .catch((error) => { if (active) setRequestError(error.message || 'Unable to load profile.'); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [sessionToken]);

  const updateField = (field, value) => {
    setForm((current) => ({ ...current, [field]: value }));
    setErrors((current) => ({ ...current, [field]: '' }));
    setNotice('');
  };

  const startEditing = () => {
    setEditing(true);
    setNotice('');
    setRequestError('');
    setErrors({});
    setForm((current) => ({ ...current, aadhaarNumber: isMasked(current.aadhaarNumber) ? '' : current.aadhaarNumber, ayushmanCardNumber: isMasked(current.ayushmanCardNumber) ? '' : current.ayushmanCardNumber }));
  };

  const saveProfile = async (event) => {
    event.preventDefault();
    const validationErrors = validateProfile(form);
    if (Object.keys(validationErrors).length) {
      setErrors(validationErrors);
      setRequestError('Please correct the highlighted fields.');
      return;
    }
    setSaving(true);
    setRequestError('');
    setNotice('');
    try {
      const response = await fetch(apiUrl('/api/profile'), {
        method: 'PUT', headers: { ...authHeaders, 'Content-Type': 'application/json' },
        body: JSON.stringify(form)
      });
      const result = await response.json();
      if (!response.ok || !result.success) throw new Error(result.message || 'Unable to save profile.');
      setForm(profileForm(result.data));
      setEditing(false);
      setNotice('Profile changes saved successfully.');
      onProfileSaved?.(result.data);
    } catch (error) {
      setRequestError(error.message || 'Unable to save profile.');
    } finally {
      setSaving(false);
    }
  };

  if (loading) return <><SectionHeading eyebrow="Account" title="Profile" copy="Your patient information and care details." /><div className="loading"><span className="spinner" /><span>Loading profile…</span></div></>;
  if (requestError && !form.name) return <><SectionHeading eyebrow="Account" title="Profile" copy="Your patient information and care details." /><div className="error-state"><strong>Profile unavailable.</strong><p>{requestError}</p><button className="secondary-button" onClick={() => window.location.reload()}>Try again</button></div></>;

  return (
    <>
      <SectionHeading eyebrow="Account" title="Profile" copy="Your patient information and care details."
        action={editing
          ? <button className="secondary-button" type="button" onClick={() => { setEditing(false); setErrors({}); setRequestError(''); }}><ArrowRight size={15} className="flip" /> Cancel</button>
          : <button className="primary-button" type="button" onClick={startEditing}><Edit3 size={15} /> Edit profile</button>} />
      <form className="profile-card profile-form" onSubmit={saveProfile}>
        <div className="profile-head">
          <span className="avatar big">PS</span>
          <div>
            <h2>{form.name || 'Patient profile'}</h2>
            <p>{form.age ? `Age ${form.age}` : 'Patient details'} · {form.mobile}</p>
            <span className="demo-chip">DEMO PATIENT</span>
          </div>
        </div>
        {requestError && <p className="profile-alert error" role="alert">{requestError}</p>}
        {notice && <p className="profile-alert success" role="status"><Check size={15} /> {notice}</p>}
        <ProfileSection icon={UserRound} title="Basic Information">
          <ProfileField label="Patient Name" error={errors.name}><input value={form.name} disabled={!editing} onChange={(event) => updateField('name', event.target.value)} /></ProfileField>
          <ProfileField label="Age" error={errors.age}><input type="number" min="0" max="120" value={form.age} disabled={!editing} onChange={(event) => updateField('age', event.target.value)} /></ProfileField>
          <ProfileField label="Gender" error={errors.gender}><select value={form.gender} disabled={!editing} onChange={(event) => updateField('gender', event.target.value)}><option value="">Select gender</option><option>Female</option><option>Male</option><option>Other</option><option>Prefer not to say</option></select></ProfileField>
        </ProfileSection>
        <ProfileSection icon={FileText} title="Identification & Government Documents">
          <ProfileField label="Aadhaar Card Number" hint="12 digits. It is masked after saving." error={errors.aadhaarNumber}><input inputMode="numeric" maxLength={12} value={form.aadhaarNumber} disabled={!editing} placeholder={editing ? 'Enter 12 digits to update' : ''} onChange={(event) => updateField('aadhaarNumber', event.target.value.replace(/\D/g, '').slice(0, 12))} /></ProfileField>
          <ProfileField label="Ayushman Bharat Card Number" hint="6-30 letters or numbers." error={errors.ayushmanCardNumber}><input maxLength={30} value={form.ayushmanCardNumber} disabled={!editing} placeholder={editing ? 'Enter card number to update' : ''} onChange={(event) => updateField('ayushmanCardNumber', event.target.value.toUpperCase().replace(/[^A-Z0-9/-]/g, ''))} /></ProfileField>
        </ProfileSection>
        <ProfileSection icon={HeartPulse} title="Medical Information">
          <ProfileField label="Height (cm)" error={errors.height}><input type="number" min="40" max="250" value={form.height} disabled={!editing} onChange={(event) => updateField('height', event.target.value)} /></ProfileField>
          <ProfileField label="Blood Group" error={errors.bloodGroup}><select value={form.bloodGroup} disabled={!editing} onChange={(event) => updateField('bloodGroup', event.target.value)}><option value="">Select blood group</option>{['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'].map((group) => <option key={group}>{group}</option>)}</select></ProfileField>
        </ProfileSection>
        <ProfileSection icon={Phone} title="Contact Information">
          <ProfileField label="Mobile Number" error={errors.mobile}><input type="tel" inputMode="numeric" value={form.mobile} disabled={!editing} onChange={(event) => updateField('mobile', event.target.value)} /></ProfileField>
          <ProfileField label="Emergency Contact Number" error={errors.emergencyContact}><input type="tel" inputMode="numeric" value={form.emergencyContact} disabled={!editing} onChange={(event) => updateField('emergencyContact', event.target.value)} /></ProfileField>
          <ProfileField label="Address" error={errors.address} wide><textarea rows="3" value={form.address} disabled={!editing} onChange={(event) => updateField('address', event.target.value)} /></ProfileField>
        </ProfileSection>
        {editing && <div className="profile-form-actions"><span><ShieldCheck size={15} /> Sensitive values are protected.</span><button className="primary-button" type="submit" disabled={saving}>{saving ? 'Saving…' : <><Save size={15} /> Save changes</>}</button></div>}
        <div className="profile-links">
          <button className="profile-link" type="button" onClick={() => go('consent')}><ShieldCheck size={18} /> <div><strong>Your data & consent</strong><span>Review what AAS can access</span></div> <ArrowRight size={15} /></button>
          <button className="profile-link" type="button" onClick={() => go('audit')}><History size={18} /> <div><strong>Recent activity</strong><span>See what happened in your account</span></div> <ArrowRight size={15} /></button>
          <button className="profile-link" type="button" onClick={() => go('documents')}><UserRound size={18} /> <div><strong>Ayushman documents</strong><span>Card and beneficiary details (demo)</span></div> <ArrowRight size={15} /></button>
        </div>
        <button className="ghost-button danger" type="button" onClick={onLogout}><LogOut size={15} /> Log out</button>
      </form>
    </>
  );
}

function ProfileSection({ icon: Icon, title, children }) {
  return <section className="profile-form-section"><div className="profile-section-heading"><span className="profile-section-icon"><Icon size={17} /></span><h2>{title}</h2></div><div className="profile-fields">{children}</div></section>;
}

function ProfileField({ label, hint, error, wide, children }) {
  return <label className={`profile-field ${wide ? 'wide' : ''}`}><span className="field-label">{label}</span>{children}{hint && <small>{hint}</small>}{error && <em>{error}</em>}</label>;
}
