import { useState } from 'react';
import {
  ArrowRight, Bell, Check, History, IdCard, Info, LogOut, Pill,
  ShieldCheck, Stethoscope, Ticket, UserRound
} from 'lucide-react';
import { SectionHeading } from '../ui';
import { consentHistory, consentItems, patient } from '../data';

// Screen 8 — Notifications (in-app; generated by prototype events).
export function Notifications({ notifications, onMarkAllRead }) {
  const unread = notifications.filter((n) => n.unread).length;
  return (
    <>
      <SectionHeading eyebrow="Stay informed" title="Notifications" copy="Helpful updates from your care journey."
        action={unread > 0 && <button className="help-link" onClick={onMarkAllRead}><Check size={15} /> Mark all read ({unread})</button>} />
      {notifications.length === 0
        ? <div className="empty-state"><Bell size={24} /><strong>No notifications yet</strong><p>Updates about tokens, medicines and follow-ups will appear here.</p></div>
        : (
          <section className="notification-list">
            {notifications.map((n) => {
              const Icon = { ticket: Ticket, pill: Pill, stethoscope: Stethoscope, idcard: IdCard }[n.icon] || Bell;
              return (
                <div className={`notification-item ${n.unread ? 'unread' : ''}`} key={n.id}>
                  <div className="notification-icon"><Icon size={19} /></div>
                  <div>
                    <span>{n.kind}</span>
                    <strong>{n.title}</strong>
                    <p>{n.body}</p>
                  </div>
                  {n.unread && <span className="unread-label">New</span>}
                </div>
              );
            })}
          </section>
        )}
      <p className="screen-note">Notifications are generated inside the prototype. No SMS is sent.</p>
    </>
  );
}

// Screen 10 — Basic consent view.
export function Consent({ consents, onToggle, go }) {
  const [showHistory, setShowHistory] = useState(false);
  return (
    <>
      <SectionHeading eyebrow="Your privacy" title="Your data & consent" copy="You decide what AAS can use. Change access any time." />
      <section className="consent-card">
        <div className="consent-header">
          <span className="consent-icon"><ShieldCheck size={22} /></span>
          <div>
            <h2>What AAS can access</h2>
            <p>Only what's needed to help you — nothing more.</p>
          </div>
        </div>
        {consentItems.map((item) => (
          <div className="consent-row" key={item.id}>
            <div className="consent-text">
              <strong>{item.label}</strong>
              <span>{item.note}</span>
            </div>
            <button
              className={`toggle ${consents[item.id] ? 'on' : ''}`}
              role="switch"
              aria-checked={consents[item.id]}
              aria-label={`${item.label} access`}
              onClick={() => onToggle(item.id)}
            >
              <i />
            </button>
            <span className={`access-badge ${consents[item.id] ? '' : 'off'}`}>
              {consents[item.id] ? <><Check size={14} /> Allowed</> : 'Blocked'}
            </span>
          </div>
        ))}
        <div className="consent-actions">
          <button className="secondary-button" onClick={() => setShowHistory(!showHistory)}><History size={16} /> View consent history</button>
          <button className="ghost-button" onClick={() => go('audit')}><Info size={15} /> See recent activity</button>
        </div>
        {showHistory && (
          <div className="consent-history">
            {consentHistory.map((entry) => (
              <div className="history-row" key={entry.when}><span className="history-dot" /><div><strong>{entry.text}</strong><time>{entry.when}</time></div></div>
            ))}
          </div>
        )}
        <p className="screen-note">Demo consent view. Legal details would sit behind an information link in the full product.</p>
      </section>
    </>
  );
}

// Screen 11 — Basic audit log (read-only).
export function Audit({ audit }) {
  return (
    <>
      <SectionHeading eyebrow="Transparency" title="Recent activity" copy="A simple read-only history of actions in your account." />
      <section className="audit-card">
        {audit.map((entry, index) => (
          <div className="audit-row" key={entry.id}>
            <time>{entry.time}</time>
            <span className="audit-dot" />
            <p>{entry.text}</p>
            {index === 0 && <span className="demo-chip">DEMO DATA</span>}
          </div>
        ))}
      </section>
      <p className="screen-note">Prototype demonstration only — not a complete audit system.</p>
    </>
  );
}

// Profile — demo account details and quick links.
export function Profile({ go, onLogout }) {
  return (
    <>
      <SectionHeading eyebrow="Account" title="Profile" copy="Your demo patient account." />
      <section className="profile-card">
        <div className="profile-head">
          <span className="avatar big">PS</span>
          <div>
            <h2>{patient.name}</h2>
            <p>Age {patient.age} · {patient.mobile} · {patient.abha}</p>
            <span className="demo-chip">DEMO PATIENT</span>
          </div>
        </div>
        <div className="profile-links">
          <button className="profile-link" onClick={() => go('consent')}><ShieldCheck size={18} /> <div><strong>Your data & consent</strong><span>Review what AAS can access</span></div> <ArrowRight size={15} /></button>
          <button className="profile-link" onClick={() => go('audit')}><History size={18} /> <div><strong>Recent activity</strong><span>See what happened in your account</span></div> <ArrowRight size={15} /></button>
          <button className="profile-link" onClick={() => go('documents')}><UserRound size={18} /> <div><strong>Ayushman documents</strong><span>Card and beneficiary details (demo)</span></div> <ArrowRight size={15} /></button>
        </div>
        <button className="ghost-button danger" onClick={onLogout}><LogOut size={15} /> Log out</button>
      </section>
    </>
  );
}
